### ISSUE TITLE
Do the build scripts in MaxAppTemplate/{{cookiecutter.project_name}}/APP/runrules work?

### ISSUE THREAD

**Issue by mikeiz404** [maxeler/MaxAppTemplate#15]
I have been having some trouble getting cookiecutter and python working on my computer so I haven't been able to test this template.

Have the build scripts in MaxAppTemplate/{{cookiecutter.project_name}}/APP/runrules been tested to work with the new split up file structure or is this still a work in progress?

**Comment by alex88bb** [comment]
This is still a work in progress.

**Comment by alixedi** [comment]
@mikeiz404 And yet, it compiles :)

@alex88bb We can in theory try and keep the master branch working at all times.

**Comment by mikeiz404** [comment]
I'm not sure if here or the google docs is the right location to have this discussion but...

The proposed directory structure in the google docs splits up a typical maxcompiler project into APP/DFE_SRC/{{PROJECT_NAME}}/{RunRules,src} and  APP/CPU_SRC/{{PROJECT_NAME}}/{build,include,src}.

At first this made sense to me but now that I think about it I'm not sure this is a good idea since...
* a maxproject is a single compilation unit and splitting them apart (imho) muddles this distinction and is inconsistent with all other projects
* I don't think this will open in maxide any more (but correct me if I'm wrong)
* the generated rules from maxide will have to be updated (at this point it might be worth writing a less complex build script)

If we keep the original maxcompiler project structure then something along the lines of APP/{{PROJECT_NAME}}/{RunRules,EngineCode, CPUCode} for maxide projects and APP/{{PROJECT_NAME}}/... for non-maxide projects, very little would have to change and they could be opened easily in maxide.

Is there a reason for the split? Thoughts?

**Comment by alex88bb** [comment]
A MaxApp is not necessarily a MaxIDE project. A MaxApp is something what will be uploaded on the App Gallery. This template makes it easier for app to be prepared for App Gallery. Everyone can develop in MaxIDE (and I don't see better way). But how are you going to include many CPU projects with many DFE projects? You are right, this will not open in MaxIDE, but if you have DFE and CPU source code, you can build everything. Or if you don't want to upload source code, just upload the binary or library (MAPI) project. I have to say one more time, this is still a work in progress and it will be available as soon as possible. Until then, apps are packed manually based on that document. That document might have some minor changes, but this should be approximately it. Another reason we are doing this is because there are nested and complicated Make files in every MaxIDE project. We are using fabricate module in Python which is much more elegant and readable. 
I hope I answered your questions. If something was not clear, feel free to ask. And other guys can confirm/refute  what I said.

**Comment by mikeiz404** [comment]
> how are you going to include many CPU projects with many DFE projects?

It seems like projects could be alongside each other in the APP directory.
The packet capture app I am working on is comprised of one C-Project and one MaxIDE project. For me this would look like APP/server/\<C-Project\> and APP/client/\<MaxIDE-Project\>.
If one doesn't want to include the EngineCode src then I believe the RunRules support this. You can specify an existing maxfile or place a generated max file in the correct RunRules directory without the dfe src.

If a MAPI/library is involved then this could exist as a MaxIDE project and other projects which need access to the EngineCode would do so through the library. These non-library projects would live alongside the MaxIDE project in the APP directory.

Is there a situation I am not thinking of?

Apologies for bringing this up so late; I did not see the document until it was finished. I was hoping that since this wasn't complete yet there was a possibility for change.

**Comment by mikeiz404** [comment]
It does seem that the MaxIDE build implementation is a bit complex for the app gallery use case however I believe going this route will require us to keep two sets of builds in sync.

**Comment by alex88bb** [comment]
I suggest you pack the app as you said in the comment:
APP/server/<C-Project>
APP/client/<MaxIDE-Project>
and we will see how it will work when we finish this app template.
It is really hard to say anything more when we still don't have anything to try.

**Comment by alixedi** [comment]
I agree with @mikeiz404 

Can we please maintain compat with MaxIDE for as long as possible. 

At the moment, this means a MaxIDE project/s living inside a MaxApp project.

@ntrifunovic

**Comment by chr1sj0nes** [comment]
Thirded. It's okay to have the C code separate from the MaxJ, but it seems o

**Comment by chr1sj0nes** [comment]
Arrgh. Clicked wrong button!

**Comment by chr1sj0nes** [comment]
I agree. As much as I hate MaxIDE projects, it is what our users now expect. Until someone can come up with something significantly better (which must integrate with MaxIDE), we should stick with them. We can still split the C code into separate projects on the apps where it makes sense and have MaxIDE projects with just EngineCode and RunRules.

**Comment by alixedi** [comment]
OK. I have had a first crack at this.

In the latest commit, you would notice a MaxIDE project living in the MaxApp. The folder structure, naming conventions as well as the .maxproject files are all in line to maintain compat with MaxIDE.

In case of issues, please let me know.

**Comment by alex88bb** [comment]
I changed it with python script, but I will revert it to previous state as Ali mentioned in previous message.

**Comment by alixedi** [comment]
Did not notice the latest commits by @alex88bb. Re-opening the issue.

**Comment by alixedi** [comment]
If we maintain compatibility with MaxIDE, we will need to keep the old build system (make+ant) alongside the new one (fabricate).

This would mean that the moment our user adds / removes / modifies some RunRule using the MaxIDE, the two build systems will be out of sync.

I do not want this.

**Comment by mikeiz404** [comment]
A few possible routes I see to maintaining MaxIDE compatibility and using fabricate:
* adapt make + ant scripts to be proxies to fabricate
* automatically generate the fabricate config from runrules / automatically generate the runrules from fabricate
* modify max ide to support fabricate
* manually keep build systems in sync

All of the above are not ideal for many reasons and most seem pretty complicated. The manual approach has the least upfront cost but will require more work in the future.

Unless there is another solution to me this boils down to: Is MaxIDE compatibility or using fabricate/having a custom build system more important for the app gallery?

**Comment by alixedi** [comment]
OK here is the sitrep:

1) I have rolled-back all the changes that broke compat with the MaxIDE. I can clone the current template, generate a project, import the APP/ folder in MaxIDE and run it without any issues.

2) I have pruned the list of people who have push access to this repo. I want to control the code quality, MaxIDE compatibility etc very tightly on this.

3) @mikeiz404 you can use this stuff. We will try and not break backward compat going forward.
